### ISSUE TITLE
Though i have pdf files in my phone, FilePicker is not showing any folders

### ISSUE THREAD

**Issue by pradeep-orbi** [arteaprogramar/Android-MaterialFilePicker#3]
Facing this issue in RealmeX2(Android-10) phone and also in OnePlus7(Android-11) phone
Following is the code i'm using
```
MaterialFilePicker()
               .withSupportFragment(this@ChooseFileUploadOptionsBottomSheet)
                // With cross icon on the right side of toolbar for closing picker straight away
                .withCloseMenu(true)
                // Showing hidden files
                .withHiddenFiles(true)
                // Want to choose only pdf files
                .withFilter(Pattern.compile(".*\\.(pdf)$"))
                // Don't apply filter to directories names
                .withFilterDirectories(false)
                .withTitle("Select PDF file to upload")
                .withRequestCode(FILE_PICKER_REQUEST_CODE)
                .start()
```

![Screenshot_2021-05-14-20-14-54-55](https://user-images.githubusercontent.com/78588549/118289043-9207c480-b4f2-11eb-945e-bddfb930baa3.jpg)
![IMG_20210514_201620](https://user-images.githubusercontent.com/78588549/118289156-ab107580-b4f2-11eb-9298-4859c5330031.jpg)
![IMG_20210514_202352](https://user-images.githubusercontent.com/78588549/118290733-638ae900-b4f4-11eb-9ed0-d021d8bd1920.jpg)

**Comment by arteaprogramar** [comment]
You need to use the following **MANAGE_EXTERNAL_STORAGE** permission.

Check the following information
https://developer.android.com/training/data-storage/manage-all-files

**Comment by pradeep-orbi** [comment]
In android-10 phone, it is working by adding `android:requestLegacyExternalStorage="true"` in manifest file. I don't know if this is the right way to do it.  
Do i have to request MANAGE_EXTERNAL_STORAGE permission, even when i limit access to single folder by setting .withRootPath(documents) using this library ?

**Comment by pradeep-orbi** [comment]
> You need to use the following **MANAGE_EXTERNAL_STORAGE** permission.
> 
> Check the following information
> https://developer.android.com/training/data-storage/manage-all-files

It is given in the documentation that we should request MANAGE_EXTERNAL_STORAGE permission only if the app's core functionality is about managing files. My use case is, i want to allow users to browse through all the folders in the phone and select pdf files for upload. 
Is there any other way that i can do without using MANAGE_EXTERNAL_STORAGE permission for my use case ?

**Comment by pradeep-orbi** [comment]
> You need to use the following **MANAGE_EXTERNAL_STORAGE** permission.
> 
> Check the following information
> https://developer.android.com/training/data-storage/manage-all-files

Can we use this library without requesting MANAGE_EXTERNAL_STORAGE permission ?

**Comment by arteaprogramar** [comment]
Hello. I have thoroughly reviewed the Google Developer documentation to understand some issues.

**First**: On Android 11 (R) or higher; the `withFilter()` method; it does not shows files according to the filter, this is because it requires the **MANAGE_EXTERNAL_STORAGE** permission to display user sensitive content.

**Second**: Unfortunately the library requires the **MANAGE_EXTERNAL_STORAGE** permission because it is considered a "File Manager".

**Comment by pradeep-orbi** [comment]
Ok. I'm using SAF(Storage Access Framework).
