### ISSUE TITLE
Not able to see file names in file picker as background and text color is white

### ISSUE THREAD

**Issue by pradeep-orbi** [arteaprogramar/Android-MaterialFilePicker#4]
Facing this issue in OnePlus3T(android-9) phone
![WhatsApp Image 2021-05-14 at 8 37 12 PM](https://user-images.githubusercontent.com/78588549/118291109-d5fbc900-b4f4-11eb-9825-87a7e6c5e145.jpeg)

**Comment by arteaprogramar** [comment]
**Its important that you add the following properties**

```
colors.xml
<resources>
    ...
    <color name="colorBackground">#fafafa</color>
    ...
</resources>

styles.xml

<resources>

    ...
    <item name="android:colorBackground">@color/colorBackground</item>
    ...
</resources>
```

**Comment by arteaprogramar** [comment]
Here is an example of how to apply previously mentioned properties

styles.xml
https://github.com/arteaprogramar/Android-MaterialFilePicker/blob/master/app/src/main/res/values/styles.xml

night/styles.xml
https://github.com/arteaprogramar/Android-MaterialFilePicker/blob/master/app/src/main/res/values-night/styles.xml

**Comment by pradeep-orbi** [comment]
> **Its important that you add the following properties**
> 
> ```
> colors.xml
> <resources>
>     ...
>     <color name="colorBackground">#fafafa</color>
>     ...
> </resources>
> 
> styles.xml
> 
> <resources>
> 
>     ...
>     <item name="android:colorBackground">@color/colorBackground</item>
>     ...
> </resources>
> ```

Yes i have already added these colors and styles, but still facing this issue. Before adding these properties, app was crashing.

**Comment by arteaprogramar** [comment]
Can you add the error log here?!

**Comment by pradeep-orbi** [comment]
I'm not using this library for now.
